### ISSUE TITLE
Peer-to-Peer Code Review - Module 2, Day 4

### ISSUE THREAD

**Issue by qwibbler** [MacCrazyman/to-do-list#2]
♻️ Great job so far implementing the to-do list!⭐ 🚀 🪐 According to our morning session, the team suggests the following changes:

## Todo:
- [ ] Consider fixing the width of the todo container
- [ ] Maybe use header semantic to make your code cleaner at https://github.com/MacCrazyman/to-do-list/blob/a5318d63792d3ac72c3ff0867c036317415c9e8a/src/index.html#L12
- [ ] You can use Unicode instead of icons:
  - &#11168;
  - &#128472;
  - &#8942;
  - link for unicode arrows [here](https://www.arrowsymbol.com/triangle-arrows-symbols)
  - just googling also works, they have very descriptive names.
- [ ] Maybe use bool instead of 0/1 at https://github.com/MacCrazyman/to-do-list/blob/a5318d63792d3ac72c3ff0867c036317415c9e8a/src/index.js#L8
- [ ] Consider using createElement instead of innerHtml as advised [here](https://www.javascripttutorial.net/javascript-dom/javascript-innerhtml-vs-createelement/)
